import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=150, help='epoch number')
parser.add_argument('--model_name', type=str, default="LFNet", help='model name')
parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')
parser.add_argument('--batchsize', type=int, default=2, help='training batch size')
parser.add_argument('--trainsize', type=int, default=256, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=100, help='every n epochs decay learning rate')
parser.add_argument('--load_mit', type=str, default=r'.\pretrained_params\pvt_v2_b2.pth', help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='0', help='train use gpu')
parser.add_argument('--rgb_root', type=str, default='./dataset/focal_stack/trainset/noargument/train_images/', help='the training rgb images root')
parser.add_argument('--fs_root', type=str, default='./dataset/focal_stack/trainset/noargument/train_focals/', help='the training depth images root')
parser.add_argument('--gt_root', type=str, default='./dataset/focal_stack/trainset/noargument/train_masks/', help='the training gt images root')
parser.add_argument('--test_rgb_root', type=str, default='./dataset/focal_stack/test_in_train/test_images/', help='the test gt images root')
parser.add_argument('--test_fs_root', type=str, default='./dataset/focal_stack/test_in_train/test_focals/', help='the test gt images root')
parser.add_argument('--test_gt_root', type=str, default='./dataset/focal_stack/test_in_train/test_masks/', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='./lfsod_cpts/', help='the path to save models and logs')
opt = parser.parse_args()